server:
  port: 443
  ssl:
   enabled: true
   key-store: www.weconn.co.kr_jks.jks
   key-store-type: JKS
   key-store-password: weconn
   key-password: weconn
  tomcat:
    use-relative-redirects: true
    max-http-form-post-size: 50MB
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
    
logging:
  level:
    org.springframework: DEBUG

spring:
  output:
    ansi:
      enabled: NEVER
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 3600

#FileUpload
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#jpa setting
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
        dialect: org.hibernate.dialect.SQLServer2008Dialect
      generate-ddl: true
      proc.param_null_passing: true
      use-new-id-generator-mappings: false

# ===================================================================
# DataSource
# ===================================================================
  datasource:    hikari:
      maximumPoolSize: 100
      onnectionTestQuery: SELECT 1
      connectionTimeout: 30000
      minimum-idle: 100
      max-lifetime: 1800000
      idle-timeout: 600000
    tomcat:
      maxactive: 100
      max-idle: 100
      min-idle: 100
      test-on-borrow: true
  datasource-erp:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:sqlserver://10.10.10.56:5555;databaseName=ERP;rewriteBatchedStatements=true;
    username : sa 
    password : dhvltm^tmxhfl
  datasource-besti:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:sqlserver://10.10.10.55:1433;databaseName=BESTIMRO;rewriteBatchedStatements=true;
    username : sa 
    password : dhvltm^tmxhfl
  datasource-sm:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:sqlserver://10.10.10.55:1433;databaseName=SM;rewriteBatchedStatements=true;
    username : sa 
    password : dhvltm^tmxhfl
  datasource-wis:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:sqlserver://10.10.10.56:5555;databaseName=WIS;rewriteBatchedStatements=true;
    username : sa 
    password : dhvltm^tmxhfl
    
#spring.datasource.driver-class-name : com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url : jdbc:sqlserver://10.10.10.55:1433;databaseName=GPPLATFORM;

# ===================================================================
# Hibernate
# ===================================================================
spring.jpa.database: sql-server
spring.jpa.properties.javax.persistence.query.timeout: 10000

# ===================================================================
# SecurityFilter
# ===================================================================
security.filter-dispatcher-types: ASYNC, FORWARD, INCLUDE, REQUEST, ERROR
security.require-ssl: true
# ===================================================================
# Logging
# ===================================================================
logging.level.org.springframework.web: info
logging.level.org.hibernate: info





